name: Update Language Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push changes back to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Example using a pre-built action (simpler)
      # You might need to find one that specifically suits your output needs
      # or write your own script.
      # This is a conceptual example; you'd replace this with actual logic.
      - name: Generate Language Stats Image
        uses: lowlighter/metrics@latest # This is a very powerful metrics generator
        with:
          token: ${{ secrets.STATS_TOKEN }}
          user: ${{ github.repository_owner }}
          # Base content configuration
          base: header, activity, community, repositories, metadata
          # Plugins
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8 # Show top 8 languages
          plugin_languages_threshold: 0% # Don't hide small languages
          plugin_languages_analysis_timeout: 15 # Timeout for language analysis
          # Options for private repositories:
          plugin_languages_ignored: '' # Ensure no languages are ignored by default if counting all
          # The 'lowlighter/metrics' action automatically includes private repos if the token has 'repo' scope.
          # You may need to check its documentation for specific flags if you want to *only* count private,
          # or fine-tune what's included. By default, with a repo-scoped token, it should count them.
          config_timezone: Europe/Paris # Optional: set your timezone
          outputs: metrics.svg # Name of the output file

      - name: Commit and Push Metrics
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add metrics.svg
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Chore: Update language metrics [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Standard token for push access
